In [1]:
import pandas as pd

READ DATA SET  AS A DATAFRAME

In [2]:
pay= pd.read_csv('City_of_Chicago_Payroll_Data.csv')

SHOW FIRST 5 RECORDS IN DATA

In [3]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN
...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN

Get the overview of your data

In [4]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

 How many 'NaN' you have in each column in your data?

In [5]:
pay.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        24775
Annual Salary         7883
Hourly Rate          24775
dtype: int64

Output the statistics for your dataset

In [6]:
pay.describe(include='all')

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
count,32658,32658,32658,32658,32658,7883.000000,24775,7883
unique,32350,1095,36,2,2,NaN,1038,167
top,"HERNANDEZ, JUAN C",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,$35.60
freq,5,9393,12973,30676,24775,NaN,2368,1404
mean,NaN,NaN,NaN,NaN,NaN,34.698719,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,9.145553,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN

What are the maximum, minimum and average Typical Hours? (use 'Typical Hours' column)

In [7]:
print('Max Typical Hours:',pay['Typical Hours'].max())
print('Min Typical Hours:',pay['Typical Hours'].min())
print('AVG Typical Hours:',pay['Typical Hours'].mean())

Max Typical Hours: 40.0
Min Typical Hours: 10.0
AVG Typical Hours: 34.69871876189268

In [8]:
pay['Department'].unique()

array(['FIRE', 'POLICE', 'LAW', 'HEALTH', 'GENERAL SERVICES',
       'WATER MGMNT', 'OEMC', 'CITY COUNCIL', 'AVIATION', 'STREETS & SAN',
       'FAMILY & SUPPORT', 'IPRA', 'PUBLIC LIBRARY', 'BUSINESS AFFAIRS',
       'TRANSPORTN', "MAYOR'S OFFICE", 'FINANCE', 'CULTURAL AFFAIRS',
       'COMMUNITY DEVELOPMENT', 'PROCUREMENT', 'BUILDINGS',
       'ANIMAL CONTRL', 'CITY CLERK', 'BOARD OF ELECTION', 'TREASURER',
       'DISABILITIES', 'HUMAN RESOURCES', 'DoIT', 'BUDGET & MGMT',
       'INSPECTOR GEN', 'HUMAN RELATIONS', 'BOARD OF ETHICS',
       'POLICE BOARD', 'ADMIN HEARNG', 'COPA', 'LICENSE APPL COMM'],
      dtype=object)

In [9]:
pay.nunique()

Name                 32350
Job Titles            1095
Department              36
Full or Part-Time        2
Salary or Hourly         2
Typical Hours            4
Annual Salary         1038
Hourly Rate            167
dtype: int64

**7. How many employees are on salary and how many are working on hourly basis?
*Hint: Group the data on 'Salary or Hourly' column. Instead of whole dataset, you can take the single column as input as well.*

In [10]:
pay.groupby('Salary or Hourly').count()

,Name,Job Titles,Department,Full or Part-Time,Typical Hours,Annual Salary,Hourly Rate
Salary or Hourly,,,,,,,
Hourly,7883,7883,7883,7883,7883,0,7883
Salary,24775,24775,24775,24775,0,24775,0

In [11]:
pay.groupby('Salary or Hourly').count()['Name']

Salary or Hourly
Hourly     7883
Salary    24775
Name: Name, dtype: int64

**8. Which department has maximum no of employees?**

In [12]:
pay['Department'].value_counts().idxmax()

'POLICE'

In [13]:
pay.groupby('Department').count()['Name'].idxmax()

'POLICE'

In [14]:
pay.groupby('Department').count().sort_values(by='Name', ascending=True)

,Name,Job Titles,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
Department,,,,,,,
LICENSE APPL COMM,1,1,1,1,0,1,0
POLICE BOARD,2,2,2,2,0,2,0
BOARD OF ETHICS,8,8,8,8,0,8,0
HUMAN RELATIONS,17,17,17,17,0,17,0
COPA,17,17,17,17,0,17,0
TREASURER,24,24,24,24,1,23,1
DISABILITIES,29,29,29,29,0,29,0
ADMIN HEARNG,38,38,38,38,0,38,0
BUDGET & MGMT,44,44,44,44,1,43,1
IPRA,56,56,56,56,0,56,0
INSPECTOR GEN,63,63,63,63,0,63,0
HUMAN RESOURCES,68,68,68,68,1,67,1
ANIMAL CONTRL,73,73,73,73,16,57,16
CULTURAL AFFAIRS,76,76,76,76,10,66,10
MAYOR'S OFFICE,85,85,85,85,7,78,7
CITY CLERK,85,85,85,85,3,82,3
PROCUREMENT,86,86,86,86,4,82,4
DoIT,101,101,101,101,0,101,0
BOARD OF ELECTION,112,112,112,112,0,112,0
BUSINESS AFFAIRS,168,168,168,168,8,160,8
COMMUNITY DEVELOPMENT,214,214,214,214,4,210,4
BUILDINGS,266,266,266,266,0,266,0
CITY COUNCIL,400,400,400,400,52,348,52
LAW,405,405,405,405,44,361,44
HEALTH,516,516,516,516,4,512,4
FINANCE,575,575,575,575,43,532,43
FAMILY & SUPPORT,621,621,621,621,300,321,300
PUBLIC LIBRARY,932,932,932,932,224,708,224
GENERAL SERVICES,972,972,972,972,767,205,767
TRANSPORTN,1103,1103,1103,1103,707,396,707
AVIATION,1612,1612,1612,1612,1056,556,1056
WATER MGMNT,1878,1878,1878,1878,1512,366,1512
OEMC,2044,2044,2044,2044,1212,832,1212
STREETS & SAN,2194,2194,2194,2194,1873,321,1873
FIRE,4800,4800,4800,4800,2,4798,2
POLICE,12973,12973,12973,12973,32,12941,32

**9. How many employees are on Salary and how many are on Hourly in the Police department?**

In [15]:
pay['Department']=='POLICE'

0        False
1         True
2        False
3        False
4         True
         ...
32653     True
32654     True
32655     True
32656     True
32657    False
Name: Department, Length: 32658, dtype: bool

In [16]:
pay[pay['Department']=='POLICE'].groupby('Salary or Hourly').count()

,Name,Job Titles,Department,Full or Part-Time,Typical Hours,Annual Salary,Hourly Rate
Salary or Hourly,,,,,,,
Hourly,32,32,32,32,32,0,32
Salary,12941,12941,12941,12941,0,12941,0

In [17]:
pay[pay['Department']=='POLICE'].groupby('Salary or Hourly').count()['Name']

Salary or Hourly
Hourly       32
Salary    12941
Name: Name, dtype: int64

10.What are the mean, max and min salaries?

In [18]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN
...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN

In [19]:
pay['Salary']= pay['Annual Salary'].str.replace('$','').astype(float)

In [20]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0

In [21]:
pay.drop(columns=['Salaryp'],inplace=True)# here i delete columnn salaryp for keyboard mistake

KeyError: "['Salaryp'] not found in axis"

In [22]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0

In [23]:
print('min:', pay['Salary'].min())
print('max:', pay['Salary'].max())  
print('mean:', pay['Salary'].mean())

min: 0.96
max: 300000.0
mean: 87512.78024137235

In [24]:
pay.head(2)

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0

11.Find an employee who has the maximum salary

In [25]:
pay[pay['Salary']==pay['Salary'].max()]

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
8310,"EVANS, GINGER S",COMMISSIONER OF AVIATION,AVIATION,F,Salary,NaN,$300000.00,NaN,300000.0

In [26]:
pay[pay['Salary']==pay['Salary'].min()]

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
15387,"KOCH, STEVEN",ADMINISTRATIVE SECRETARY,MAYOR'S OFFICE,F,Salary,NaN,$0.96,NaN,0.96

12. Find an employee who has the minimum salary [another way using idxmax)

In [27]:
pay['Salary'].idxmax() #[idxmax show which row has maximum value]

8310

In [28]:
pay.iloc[8310] #[here through i loc we can get whole row details ]

Name                         EVANS,  GINGER S
Job Titles           COMMISSIONER OF AVIATION
Department                           AVIATION
Full or Part-Time                           F
Salary or Hourly                       Salary
Typical Hours                             NaN
Annual Salary                      $300000.00
Hourly Rate                               NaN
Salary                               300000.0
Name: 8310, dtype: object

In [29]:
pay.loc[pay['Salary'].idxmax()]

Name                         EVANS,  GINGER S
Job Titles           COMMISSIONER OF AVIATION
Department                           AVIATION
Full or Part-Time                           F
Salary or Hourly                       Salary
Typical Hours                             NaN
Annual Salary                      $300000.00
Hourly Rate                               NaN
Salary                               300000.0
Name: 8310, dtype: object

In [30]:
pay.loc[pay['Salary'].idxmin()]

Name                           KOCH,  STEVEN
Job Titles           ADMINISTRATIVE SECRETARY
Department                     MAYOR'S OFFICE
Full or Part-Time                           F
Salary or Hourly                       Salary
Typical Hours                             NaN
Annual Salary                           $0.96
Hourly Rate                               NaN
Salary                                   0.96
Name: 15387, dtype: object

In [31]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0

**13. What are the mean, max and min Hourly Rate?**
use.str and replace()
Hint:
Once again, create a new column name "H_Rate" and separate the number from dollar sign as float

In [32]:
pay['H_Rate']=pay['Hourly Rate'].str.replace('$','').astype(float)

In [33]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

In [34]:
print('Min hour rate:',pay['H_Rate'].min())
print('Max hour rate:',pay['H_Rate'].max())
print('Avg hour rate:',pay['H_Rate'].mean())

Min hour rate: 2.65
Max hour rate: 96.0
Avg hour rate: 32.86819231257135

**14. How many employees are getting max Hourly Rate?**

In [35]:
pay[pay['H_Rate']==pay['H_Rate'].max()].count()

Name                 1
Job Titles           1
Department           1
Full or Part-Time    1
Salary or Hourly     1
Typical Hours        1
Annual Salary        0
Hourly Rate          1
Salary               0
H_Rate               1
dtype: int64

In [36]:
pay[pay['H_Rate']==pay['H_Rate'].max()].count()['Name']

np.int64(1)

**15. Who is getting max Hourly Rate?**

In [37]:
pay.loc[pay['H_Rate'].idxmax()]

Name                 JONES,  JOHN W
Job Titles             PSYCHIATRIST
Department                   HEALTH
Full or Part-Time                 F
Salary or Hourly             Hourly
Typical Hours                  35.0
Annual Salary                   NaN
Hourly Rate                  $96.00
Salary                          NaN
H_Rate                         96.0
Name: 14317, dtype: object

In [38]:
pay[pay['H_Rate']== pay['H_Rate'].max()] # another way

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
14317,"JONES, JOHN W",PSYCHIATRIST,HEALTH,F,Hourly,35.0,NaN,$96.00,NaN,96.0

**16. How many employees are earning less than the average Hourly Rate?**

In [39]:
pay[pay['H_Rate']< pay['H_Rate'].mean()].count()

Name                 2791
Job Titles           2791
Department           2791
Full or Part-Time    2791
Salary or Hourly     2791
Typical Hours        2791
Annual Salary           0
Hourly Rate          2791
Salary                  0
H_Rate               2791
dtype: int64

In [40]:
pay[pay['H_Rate']< pay['H_Rate'].mean()].count()['Name']

np.int64(2791)

**17. How many employees are paid hourly and they have full-time job?**

In [41]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

In [42]:
pay[(pay['Salary or Hourly']=='Hourly')&(pay['Full or Part-Time']=='F')].count()

Name                 5906
Job Titles           5906
Department           5906
Full or Part-Time    5906
Salary or Hourly     5906
Typical Hours        5906
Annual Salary           0
Hourly Rate          5906
Salary                  0
H_Rate               5906
dtype: int64

In [43]:
pay[(pay['Salary or Hourly']=='Hourly')&(pay['Full or Part-Time']=='F')].count()['Name']

np.int64(5906)

**18. Find the full-time employees who are working at hourly rate of $10.00?**

In [44]:
pay[(pay['Full or Part-Time']=='F') & (pay['H_Rate']==10)]

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
1232,"AYALA JR, JESUS",STUDENT INTERN,HUMAN RESOURCES,F,Hourly,35.0,NaN,$10.00,NaN,10.0
4522,"CERVANTES, BIANCA A",STUDENT INTERN,BUDGET & MGMT,F,Hourly,35.0,NaN,$10.00,NaN,10.0
6476,"DAVILA, ROBERTO A",ALDERMANIC AIDE,CITY COUNCIL,F,Hourly,35.0,NaN,$10.00,NaN,10.0
16474,"LEVY, ETHAN",CLERK CITY COUNCIL,CITY COUNCIL,F,Hourly,35.0,NaN,$10.00,NaN,10.0

**19. How many unique Job Titles are there in the data?**

In [45]:
pay['Job Titles'].nunique()

1095

In [46]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

**20. What was the average Salary of the employees in each department?**

In [50]:
pay.groupby('Department')['Salary'].mean()

Department
ADMIN HEARNG             78912.947368
ANIMAL CONTRL            66089.684211
AVIATION                 76140.018777
BOARD OF ELECTION        56051.142857
BOARD OF ETHICS          94552.500000
BUDGET & MGMT            93925.395349
BUILDINGS                98864.833534
BUSINESS AFFAIRS         80446.425000
CITY CLERK               69762.439024
CITY COUNCIL             63577.172069
COMMUNITY DEVELOPMENT    88363.257143
COPA                     98784.705882
CULTURAL AFFAIRS         87048.909091
DISABILITIES             82431.724138
DoIT                     99681.029703
FAMILY & SUPPORT         79013.588785
FINANCE                  73276.364662
FIRE                     97762.348662
GENERAL SERVICES         83095.528390
HEALTH                   85488.210938
HUMAN RELATIONS          93778.588235
HUMAN RESOURCES          79851.761194
INSPECTOR GEN            84030.666667
IPRA                     94429.285714
LAW                      84582.814404
LICENSE APPL COMM        80568.000000
MAYOR'S OFFICE           96165.512308
OEMC                     73153.778221
POLICE                   87836.025349
POLICE BOARD             86136.000000
PROCUREMENT              83278.243902
PUBLIC LIBRARY           71273.288136
STREETS & SAN            84347.775701
TRANSPORTN               89976.896061
TREASURER                88062.652174
WATER MGMNT              89894.111803
Name: Salary, dtype: float64

In [51]:
pay.groupby('Department')['Salary'].max()

Department
ADMIN HEARNG             156420.0
ANIMAL CONTRL            130008.0
AVIATION                 300000.0
BOARD OF ELECTION        133740.0
BOARD OF ETHICS          135672.0
BUDGET & MGMT            169992.0
BUILDINGS                157092.0
BUSINESS AFFAIRS         157092.0
CITY CLERK               125292.0
CITY COUNCIL             160248.0
COMMUNITY DEVELOPMENT    175020.0
COPA                     161856.0
CULTURAL AFFAIRS         155040.0
DISABILITIES             138420.0
DoIT                     154992.0
FAMILY & SUPPORT         175002.0
FINANCE                  165000.0
FIRE                     202728.0
GENERAL SERVICES         157092.0
HEALTH                   177000.0
HUMAN RELATIONS          125004.0
HUMAN RESOURCES          151572.0
INSPECTOR GEN            161856.0
IPRA                     122316.0
LAW                      173664.0
LICENSE APPL COMM         80568.0
MAYOR'S OFFICE           216210.0
OEMC                     167796.0
POLICE                   260004.0
POLICE BOARD             105792.0
PROCUREMENT              167220.0
PUBLIC LIBRARY           167004.0
STREETS & SAN            157092.0
TRANSPORTN               169500.0
TREASURER                137700.0
WATER MGMNT              169512.0
Name: Salary, dtype: float64

In [47]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

**21. What is the job title of 'AGAR,  BULENT B'?** please note, there are two spaces between AGAR, and BULENT.

In [56]:
pay[pay['Name']== 'AGAR,  BULENT B']['Job Titles']

230    CHIEF ENGINEER OF SEWERS
Name: Job Titles, dtype: object

**22. What are the top most common job titles?**

In [57]:
pay['Job Titles'].value_counts()

Job Titles
POLICE OFFICER                            9393
FIREFIGHTER-EMT                           1424
SERGEANT                                  1118
POOL MOTOR TRUCK DRIVER                    996
POLICE OFFICER (ASSIGNED AS DETECTIVE)     845
                                          ...
MICROBIOLOGIST IV                            1
FIRST DEPUTY CHIEF ADMINISTRATOR             1
COMMISSIONER OF HUMAN RESOURCES              1
CHIEF INVESTIGATIVE LAW OFFICER              1
MECHANICAL ENGINEER IV                       1
Name: count, Length: 1095, dtype: int64

**23. How many people have the word 'officer' in their job title? (This is pretty tricky)**

In [61]:
def find_string(title):
    if 'officer' in title.lower():
        return True
    else:
        return False

In [62]:
pay['Job Titles'].apply(find_string)

0        False
1        False
2        False
3        False
4        False
         ...
32653     True
32654     True
32655     True
32656     True
32657    False
Name: Job Titles, Length: 32658, dtype: bool

In [63]:
pay['Job Titles'].apply(find_string).sum()

np.int64(11101)

In [64]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN
...,...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,NaN,90024.0,NaN
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,$48078.00,NaN,48078.0,NaN
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,$87006.00,NaN,87006.0,NaN
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,$93354.00,NaN,93354.0,NaN
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,$115932.00,NaN,115932.0,NaN

**24. Save the final dataframe to a csv file**

In [67]:
pay.to_csv('xyz.csv')